(function(){'use strict';
var rows=document.getElementById('referral-withdrawal-rows'),message=document.getElementById('cabinet-admin-message');
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function request(url,options){return fetch(url,Object.assign({headers:{'Content-Type':'application/json'}},options)).then(function(r){return r.json().catch(function(){return{}}).then(function(d){if(!r.ok)throw new Error(d.error||'Ошибка');return d})})}
function load(){if(!rows)return;request('/api/admin/cabinet/withdrawals').then(function(items){rows.innerHTML=items.map(function(x){return '<tr><td>'+new Date(x.created_at).toLocaleString('ru-RU')+'</td><td>'+esc((x.amount_kopecks/100).toFixed(2))+' ₽</td><td>'+esc(x.bank_name)+' · '+esc(x.sbp_phone)+'</td><td>'+esc(x.status)+'</td><td><button class="btn admin-mini-btn" data-id="'+x.id+'" data-status="approved">Одобрить</button> <button class="btn admin-mini-btn" data-id="'+x.id+'" data-status="paid">Выплачено</button> <button class="btn admin-mini-btn" data-id="'+x.id+'" data-status="rejected">Отклонить</button></td></tr>'}).join('')}).catch(function(e){message.textContent=e.message})}
if(rows)rows.addEventListener('click',function(e){var b=e.target.closest('button[data-id]');if(!b)return;request('/api/admin/cabinet/withdrawal',{method:'PATCH',body:JSON.stringify({id:b.dataset.id,status:b.dataset.status})}).then(load).catch(function(err){message.textContent=err.message})});
var send=document.getElementById('product-news-send');if(send)send.onclick=function(){request('/api/admin/cabinet/news',{method:'POST',body:JSON.stringify({title:document.getElementById('product-news-title').value,body:document.getElementById('product-news-body').value,link:document.getElementById('product-news-link').value})}).then(function(d){message.textContent='Отправлено: '+d.sent}).catch(function(e){message.textContent=e.message})};
document.addEventListener('DOMContentLoaded',load);load();
})();
