(function(){'use strict';
var KEY='sticker_generation_history_v1',ACCESS='sticker_access_code',PACKAGE='sticker_purchased_package',originalFetch=window.fetch.bind(window);
function read(k,f){try{return JSON.parse(localStorage.getItem(k))||f;}catch(e){return f;}}function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));}catch(e){}}function list(){var v=read(KEY,[]);return Array.isArray(v)?v:[];}
function save(data,options){var body={};try{body=JSON.parse(options.body||'{}');}catch(e){}var box=body.mode==='box_range'||body.mode==='box_custom',custom=body.mode==='custom'||body.mode==='box_custom',item=custom?{id:(box?'bc-':'c-')+Date.now(),mode:'custom',category:box?'box':'product',prefix:data.prefix||'',createdAt:new Date().toISOString(),quantity:1,code:data.code,imageUrl:data.imageUrl}:{id:data.batchId||'r-'+Date.now(),mode:'range',category:box?'box':'product',prefix:data.prefix||'',createdAt:new Date().toISOString(),quantity:data.stickers.length,stickers:data.stickers,pdfUrl:data.pdfUrl};var all=list();all.unshift(item);write(KEY,all.slice(0,100));render();}
window.fetch=function(input,options){var url=typeof input==='string'?input:(input&&input.url)||'';return originalFetch(input,options).then(function(response){if(url.indexOf('/api/stickers/generate')===0&&options&&options.method==='POST'&&response.ok)response.clone().json().then(function(data){save(data,options);}).catch(function(){});return response;});};
function btn(text,fn){var b=document.createElement('button');b.className='btn';b.type='button';b.textContent=text;b.onclick=fn;return b;}
function urls(item){return item.mode==='range'?item.stickers.map(function(s){return s.imageUrl;}):[item.imageUrl];}
function show(item){var preview=document.getElementById('sticker-preview');if(!preview)return;preview.innerHTML='';urls(item).forEach(function(url,i){var f=document.createElement('figure'),img=document.createElement('img');f.className='sticker-card';img.src=url;img.alt=item.mode==='range'?'Возвратный стикер '+item.stickers[i].code:'Стикер '+item.code;f.appendChild(img);preview.appendChild(f);});preview.scrollIntoView({behavior:'smooth',block:'start'});}
function renderPackage(box,code){if(!/^\d{6}$/.test(code))return;var fallback=read(PACKAGE,null),card=document.createElement('div'),info=document.createElement('div'),actions=document.createElement('div');card.className='history-package-card';info.innerHTML='<div class="history-batch-title">Купленный пакет</div><strong class="history-code">'+code+'</strong><div id="history-live-limits" class="history-limits">Проверяем остаток…</div><div class="history-batch-meta">Код можно передать другому человеку. Остаток пакета будет общим.</div>';actions.appendChild(btn('Скопировать код',function(){if(navigator.clipboard)navigator.clipboard.writeText(code);}));card.appendChild(info);card.appendChild(actions);box.appendChild(card);originalFetch('/api/stickers/generate?accessCode='+encodeURIComponent(code)).then(function(r){if(!r.ok)throw new Error();return r.json();}).then(function(d){var a=d.access,node=document.getElementById('history-live-limits');if(node)node.innerHTML='<strong>Товары:</strong> массово осталось '+a.range.remaining+', по номеру '+a.custom.remaining+'<br><strong>Коробки:</strong> массово осталось '+a.boxRange.remaining+', по номеру '+a.boxCustom.remaining;}).catch(function(){var node=document.getElementById('history-live-limits');if(node&&fallback)node.textContent='Данные пакета сохранены локально';});}
function niimbot(item,status){if(!window.NiimbotWeb){status.textContent='Печать NIIMBOT недоступна.';return;}window.NiimbotWeb.printImages(urls(item),function(c,t){status.textContent='Печать '+c+' из '+t+'…';}).then(function(){status.textContent='Партия отправлена на NIIMBOT.';}).catch(function(e){status.textContent=e.message||'Ошибка печати.';});}
function render(){var section=document.getElementById('user-history'),packages=document.getElementById('history-package'),batches=document.getElementById('history-batches');if(!section||!packages||!batches)return;var all=list(),code='';try{code=localStorage.getItem(ACCESS)||'';}catch(e){}packages.innerHTML='';batches.innerHTML='';renderPackage(packages,code);all.forEach(function(item){var row=document.createElement('article'),info=document.createElement('div'),actions=document.createElement('div'),status=document.createElement('div'),box=item.category==='box',title=item.mode==='range'?(box?'QR коробок: ':'Стикеры товаров: ')+item.quantity:(box?'QR коробки: '+(item.prefix||'')+item.code:'Стикер товара: '+item.code);row.className='history-batch';actions.className='history-batch-actions';status.className='history-batch-meta';info.innerHTML='<div class="history-batch-title">'+title+'</div><div class="history-batch-meta">'+new Date(item.createdAt).toLocaleString('ru-RU')+'</div>';info.appendChild(status);actions.appendChild(btn('Открыть',function(){show(item);}));if(item.pdfUrl){var pdf=document.createElement('a');pdf.className='btn';pdf.href=item.pdfUrl;pdf.textContent='PDF A4';actions.appendChild(pdf);}actions.appendChild(btn('Обычная печать',function(){show(item);setTimeout(function(){window.print();},150);}));actions.appendChild(btn('NIIMBOT',function(){niimbot(item,status);}));row.appendChild(info);row.appendChild(actions);batches.appendChild(row);});section.hidden=!all.length&&!/^\d{6}$/.test(code);}
document.addEventListener('DOMContentLoaded',function(){var clear=document.getElementById('history-clear');if(clear)clear.onclick=function(){if(confirm('Удалить историю стикеров из этого браузера?')){try{localStorage.removeItem(KEY);}catch(e){}render();}};render();});
})();
