(function(){'use strict';var button=document.getElementById('program-buy'),consent=document.getElementById('program-consent'),error=document.getElementById('program-payment-error'),promoToggle=document.getElementById('promo-toggle'),promoForm=document.getElementById('promo-form'),promoInput=document.getElementById('program-promo'),promoApply=document.getElementById('promo-apply');if(!button)return;
fetch('/api/payments/config').then(function(response){return response.json();}).then(function(config){if(!config.enabled){button.disabled=true;button.textContent='Оплата скоро будет доступна';}}).catch(function(){button.disabled=true;button.textContent='Оплата временно недоступна';});
button.onclick=function(){error.textContent='';if(!consent.checked){error.textContent='Примите оферту и политику конфиденциальности.';return;}button.disabled=true;fetch('/api/payments/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productKind:'program',accepted:true})}).then(function(response){return response.json().then(function(body){if(!response.ok)throw new Error(body.error||'Ошибка оплаты');return body;});}).then(function(data){location.href=data.confirmationUrl;}).catch(function(reason){error.textContent=reason.message;button.disabled=false;});};
promoToggle.onclick=function(){var opening=promoForm.hidden;promoForm.hidden=!opening;promoToggle.setAttribute('aria-expanded',String(opening));if(opening)promoInput.focus();};
promoApply.onclick=function(){error.textContent='';var code=(promoInput.value||'').trim();if(!consent.checked){error.textContent='Примите оферту и политику конфиденциальности.';return;}if(!code){error.textContent='Введите промокод.';return;}promoApply.disabled=true;fetch('/api/payments/promo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({promoCode:code,accepted:true})}).then(function(response){return response.json().then(function(body){if(!response.ok)throw new Error(body.error||'Промокод не принят');return body;});}).then(function(data){location.href=data.downloadUrl;}).catch(function(reason){error.textContent=reason.message;promoApply.disabled=false;});};promoInput.addEventListener('keydown',function(event){if(event.key==='Enter')promoApply.click();});
var licenseBuy=document.getElementById('license-buy'),licenseConsent=document.getElementById('license-consent'),licenseError=document.getElementById('license-payment-error'),licensePrices={1:25,3:40,5:50,10:90,20:150};
function selectedLicense(){var selected=document.querySelector('input[name="license-package"]:checked');return selected?Number(selected.value):0;}
document.querySelectorAll('input[name="license-package"]').forEach(function(input){input.onchange=function(){var iterations=selectedLicense();licenseBuy.textContent='Купить '+iterations+' '+(iterations===1?'итерацию':'итераций')+' за '+licensePrices[iterations]+' ₽';};});
licenseBuy.onclick=function(){licenseError.textContent='';var iterations=selectedLicense();if(!licenseConsent.checked){licenseError.textContent='Примите оферту и политику конфиденциальности.';return;}licenseBuy.disabled=true;fetch('/api/payments/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productKind:'program_license',licenseIterations:iterations,accepted:true})}).then(function(response){return response.json().then(function(body){if(!response.ok)throw new Error(body.error||'Ошибка оплаты');return body;});}).then(function(data){location.href=data.confirmationUrl;}).catch(function(reason){licenseError.textContent=reason.message;licenseBuy.disabled=false;});};})();
