import { useEffect,useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Bell,Lock,Printer,Trash2 } from 'lucide-react';
import { Alert,Button,Card,Checkbox,Field,Input,Modal,Select,Tabs,useToast } from '../../ui';
import { CabinetError,CabinetLoading } from '../../components/CabinetState';
import { useCabinet,useCabinetMutation } from '../../api/cabinet';
import { useStores } from '../../stores/root-store';
import { getSupabase } from '../../auth/supabase';
import { useDocumentMeta } from '../../lib/seo';
import { THERMAL_SIZES } from '../../lib/thermal-print';

function Security(){const {auth}=useStores();const toast=useToast();const [current,setCurrent]=useState(''),[next,setNext]=useState(''),[repeat,setRepeat]=useState(''),[busy,setBusy]=useState(false);const change=async()=>{if(next.length<8||next!==repeat)return toast('Проверьте новый пароль','error');if(!auth.user?.email||auth.user.email.endsWith('@users.invalid'))return toast('Сначала добавьте почту и пароль в профиле','error');setBusy(true);try{const {error}=await getSupabase().auth.signInWithPassword({email:auth.user.email,password:current});if(error)throw new Error('Неверный текущий пароль');await auth.updatePassword(next);setCurrent('');setNext('');setRepeat('');toast('Пароль изменён','success')}catch(e){toast(e instanceof Error?e.message:'Не удалось изменить пароль','error')}finally{setBusy(false)}};return <Card><h2>Смена пароля</h2><div className="stack"><Field label="Текущий пароль"><Input type="password" value={current} onChange={e=>setCurrent(e.target.value)}/></Field><Field label="Новый пароль"><Input type="password" value={next} onChange={e=>setNext(e.target.value)}/></Field><Field label="Повторите пароль"><Input type="password" value={repeat} onChange={e=>setRepeat(e.target.value)}/></Field><Button loading={busy} onClick={change}>Сменить пароль</Button></div></Card>}
function Notifications(){const query=useCabinet();const mutation=useCabinetMutation<Record<string,boolean>>('/api/cabinet/preferences','PATCH');const toast=useToast();const p=query.data!.profile.preferences;const save=(key:string,value:boolean)=>mutation.mutate({[key]:value},{onSuccess:()=>toast('Настройка сохранена','success')});return <Card><h2>Уведомления</h2><div className="stack"><Checkbox checked={p.notifyKeyExpiry} onChange={e=>save('notifyKeyExpiry',e.target.checked)}>Окончание срока ключей</Checkbox><Checkbox checked={p.notifyOrderStatus} onChange={e=>save('notifyOrderStatus',e.target.checked)}>Статус заказов</Checkbox><Checkbox checked={p.notifyLowBalance} onChange={e=>save('notifyLowBalance',e.target.checked)}>Низкий остаток пакета</Checkbox><Checkbox checked={p.notifyProductNews} onChange={e=>save('notifyProductNews',e.target.checked)}>Новости продуктов</Checkbox></div></Card>}
// Список размеров общий с генератором. «Плотность» отсюда убрана: ни печать
// через драйвер, ни протокол NIIMBOT её не используют — настройка сохранялась в
// базу и ни на что не влияла.
function Thermal(){const query=useCabinet();const toast=useToast();const mutation=useCabinetMutation<{thermalPrintSettings:Record<string,unknown>}>('/api/cabinet/preferences','PATCH');const initial=query.data!.profile.preferences.thermalPrintSettings;const [size,setSize]=useState(String(initial.size||'58x40')),[printer,setPrinter]=useState(String(initial.printer||'system'));return <Card><h2>Термопечать</h2><p className="muted">Размер подставится в генераторе при печати по одной этикетке.</p><div className="stack"><Field label="Размер этикетки"><Select value={size} onChange={e=>setSize(e.target.value)}>{THERMAL_SIZES.filter(item=>item.value!=='custom').map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</Select></Field><Field label="Принтер"><Select value={printer} onChange={e=>setPrinter(e.target.value)}><option value="system">Системный Windows</option><option value="tsc">TSC</option><option value="niimbot">NIIMBOT</option></Select></Field><Button onClick={()=>mutation.mutate({thermalPrintSettings:{size,printer}},{onSuccess:()=>toast('Настройки сохранены','success')})}>Сохранить</Button></div></Card>}
function Danger(){const {auth}=useStores();const navigate=useNavigate();const [open,setOpen]=useState(false),[confirm,setConfirm]=useState('');const remove=useCabinetMutation<{confirmation:string}>('/api/cabinet/account','DELETE');useEffect(()=>{if(remove.isSuccess){void auth.signOut();navigate('/')}},[remove.isSuccess,auth,navigate]);return <><Card><h2>Удаление аккаунта</h2><p className="muted">История и профиль будут удалены, ключи продолжат работать без привязки. Реферальный баланс будет аннулирован.</p><Button variant="danger" onClick={()=>setOpen(true)}>Удалить аккаунт</Button></Card><Modal open={open} onOpenChange={setOpen} title="Удалить аккаунт?"><div className="stack"><Alert tone="warning">Перед удалением войдите повторно. Действие необратимо.</Alert><Field label="Введите УДАЛИТЬ"><Input value={confirm} onChange={e=>setConfirm(e.target.value.toUpperCase())}/></Field><Button variant="danger" disabled={confirm!=='УДАЛИТЬ'} loading={remove.isPending} onClick={()=>remove.mutate({confirmation:confirm})}><Trash2 size={16}/>Удалить навсегда</Button>{remove.isError&&<Alert tone="error">{remove.error.message}</Alert>}</div></Modal></>}
export function SettingsPage(){useDocumentMeta('Настройки — кабинет');const query=useCabinet();if(query.isPending)return <div className="page"><CabinetLoading/></div>;if(query.isError)return <div className="page"><CabinetError error={query.error} retry={()=>query.refetch()}/></div>;return <div className="page"><header className="page-head"><h1>Настройки</h1><p>Безопасность, уведомления, печать и управление аккаунтом.</p></header><Tabs label="Разделы настроек" items={[{value:'security',label:'Безопасность',icon:<Lock size={16}/>,content:<Security/>},{value:'notifications',label:'Уведомления',icon:<Bell size={16}/>,content:<Notifications/>},{value:'print',label:'Термопечать',icon:<Printer size={16}/>,content:<Thermal/>},{value:'danger',label:'Аккаунт',icon:<Trash2 size={16}/>,content:<Danger/>}]}/></div>}
