const crypto = require('crypto');
const { boxStickerSvg, stickerSvg } = require('../_stickers');
const { supabaseFetch } = require('../_supabase');

module.exports = async function handler(req, res) {
  if (req.method !== 'GET') return res.status(405).end();
  const example = String(req.query?.example || '') === '1';
  const batch = String(req.query?.batch || '');
  const code = example ? '69874145048' : String(req.query?.code || '');
  const token = String(req.query?.token || '');
  const variant = String(req.query?.variant || '');
  const prefix = String(req.query?.prefix || 'TRBX').toUpperCase();
  if (!/^\d{1,12}$/.test(code)) return res.status(400).end();
  try {
    if (example) {
      // Public preview generated by the same server template as real stickers.
    } else if (token) {
      if (!process.env.STICKER_CLIENT_SECRET) return res.status(500).end();
      const signedValue = variant === 'box' ? `${prefix}:${code}` : code;
      const expected = crypto.createHmac('sha256', process.env.STICKER_CLIENT_SECRET).update(signedValue).digest('base64url');
      const left = Buffer.from(token); const right = Buffer.from(expected);
      if (left.length !== right.length || !crypto.timingSafeEqual(left, right)) return res.status(403).end();
    } else {
      if (!/^[0-9a-f-]{36}$/i.test(batch)) return res.status(400).end();
      const table=variant==='box'?'return_box_codes':'return_sticker_codes';
      const rows = await supabaseFetch(`${table}?batch_id=eq.${encodeURIComponent(batch)}&code=eq.${encodeURIComponent(code)}&select=code`);
      if (!rows.length) return res.status(404).end();
    }
    const svg = variant === 'box' ? await boxStickerSvg(prefix, code) : await stickerSvg(code);
    res.setHeader('Content-Type', 'image/svg+xml; charset=utf-8');
    res.setHeader('Cache-Control', example ? 'public, max-age=86400' : 'private, max-age=3600');
    return res.status(200).send(svg);
  } catch (error) {
    console.error(error);
    return res.status(502).end();
  }
};
