const crypto = require('crypto');
const { boxStickerSvg, stickerSvg } = require('../../server/_stickers');
const { supabaseFetch } = require('../../server/_supabase');
const { requireUser } = require('../../server/_user-auth');
const path = require('path');
const { Resvg } = require('@resvg/resvg-js');

function embedPreviewFont(svg) {
  return svg.replace(/<svg[^>]*>/, match => `${match}<style>text{font-family:Inter!important}</style>`);
}

module.exports = async function handler(req, res) {
  if (req.method !== 'GET') return res.status(405).end();
  const example = String(req.query?.example || '') === '1';
  const batch = String(req.query?.batch || '');
  const historyId = String(req.query?.history || '');
  const code = example ? '69874145048' : String(req.query?.code || '');
  const token = String(req.query?.token || '');
  const expires = Number(req.query?.expires || 0);
  let variant = String(req.query?.variant || '');
  let prefix = String(req.query?.prefix || 'TRBX').toUpperCase();
  if (!/^\d{1,12}$/.test(code)) return res.status(400).end();
  try {
    if (example) {
      // Public preview generated by the same server template as real stickers.
    } else if (historyId) {
      if (!/^\d+$/.test(historyId)) return res.status(400).end();
      const user = await requireUser(req, res); if (!user) return;
      const history = await supabaseFetch(`user_generation_history?id=eq.${encodeURIComponent(historyId)}&user_id=eq.${encodeURIComponent(user.id)}&select=payload&limit=1`);
      if (!history.length) return res.status(404).end();
      const payload = history[0].payload || {};
      const codes = Array.isArray(payload.codes) && payload.codes.length ? payload.codes : (payload.code ? [payload.code] : []);
      if (!codes.some(value => String(value) === code)) return res.status(404).end();
      variant = payload.category === 'box' ? 'box' : 'product';
      prefix = String(payload.prefix || 'TRBX').toUpperCase();
      if (variant === 'box' && !/^[A-Z0-9_-]{1,12}$/.test(prefix)) return res.status(400).end();
    } else if (token) {
      if (!process.env.STICKER_CLIENT_SECRET) return res.status(500).end();
      const now=Math.floor(Date.now()/1000);
      if(!Number.isInteger(expires)||expires<now||expires>now+3700)return res.status(403).end();
      const signedValue = `${variant === 'box' ? `${prefix}:${code}` : code}:${expires}`;
      const expected = crypto.createHmac('sha256', process.env.STICKER_CLIENT_SECRET).update(signedValue).digest('base64url');
      const left = Buffer.from(token); const right = Buffer.from(expected);
      if (left.length !== right.length || !crypto.timingSafeEqual(left, right)) return res.status(403).end();
    } else {
      if (!/^[0-9a-f-]{36}$/i.test(batch)) return res.status(400).end();
      const table=variant==='box'?'return_box_codes':'return_sticker_codes';
      const rows = await supabaseFetch(`${table}?batch_id=eq.${encodeURIComponent(batch)}&code=eq.${encodeURIComponent(code)}&select=code`);
      if (!rows.length) return res.status(404).end();
    }
    const svg = variant === 'box' ? await boxStickerSvg(prefix, code) : await stickerSvg(code);
    if (String(req.query?.format || '') === 'png') {
      const renderer = new Resvg(embedPreviewFont(svg), {
        font: {
          fontFiles: [path.join(process.cwd(), 'server', 'assets', 'InterVariable.ttf')],
          loadSystemFonts: false,
          defaultFontFamily: 'Inter',
        },
      });
      const png = renderer.render().asPng();
      res.setHeader('Content-Type', 'image/png');
      res.setHeader('Cache-Control', example ? 'public, max-age=86400' : 'private, max-age=3600');
      return res.status(200).send(Buffer.from(png));
    }
    res.setHeader('Content-Type', 'image/svg+xml; charset=utf-8');
    res.setHeader('Cache-Control', example ? 'public, max-age=86400' : 'private, max-age=3600');
    return res.status(200).send(svg);
  } catch (error) {
    console.error(error);
    return res.status(502).end();
  }
};
