begin;

create table if not exists public.cell_print_licenses (
  id bigint generated by default as identity primary key,
  key text not null unique,
  duration_days integer not null check (duration_days between 1 and 4000),
  device_limit integer not null check (device_limit in (1,2,3,5)),
  active boolean not null default true,
  activated_at timestamptz,
  expires_at timestamptz,
  source text not null default 'admin',
  note text not null default '' check (char_length(note) <= 200),
  created_at timestamptz not null default now()
);

create table if not exists public.cell_print_activations (
  id bigint generated by default as identity primary key,
  license_id bigint not null references public.cell_print_licenses(id) on delete cascade,
  device_hash text not null check (length(device_hash) = 64),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique(license_id, device_hash)
);

create table if not exists public.cell_print_promocodes (
  id bigint generated by default as identity primary key,
  code text not null unique check (code = upper(code) and code ~ '^[A-Z0-9_-]{3,32}$'),
  discount_percent integer not null check (discount_percent between 1 and 100),
  scope text not null default 'all' check (scope in ('program','license','all')),
  usage_limit integer not null default 1 check (usage_limit between 1 and 100000),
  used integer not null default 0 check (used between 0 and usage_limit),
  expires_at timestamptz,
  active boolean not null default true,
  note text not null default '' check (char_length(note) <= 200),
  created_at timestamptz not null default now()
);

create table if not exists public.cell_print_announcements (
  id bigint generated by default as identity primary key,
  text text not null check (length(btrim(text)) > 0),
  url text not null default '', button text not null default '',
  level text not null default 'info' check (level in ('info','warning','important')),
  starts_at timestamptz, ends_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.cell_print_releases (
  id boolean primary key default true check (id),
  version text not null default '1.0.0', minimum_version text not null default '1.0.0',
  download_url text not null default '', notes text not null default '',
  mandatory boolean not null default false, updated_at timestamptz not null default now()
);
insert into public.cell_print_releases(id) values(true) on conflict(id) do nothing;

alter table public.payment_orders drop constraint if exists payment_orders_product_kind_check;
alter table public.payment_orders add constraint payment_orders_product_kind_check check
  (product_kind in ('stickers','program','program_license','cell_print_program','cell_print_license','cell_print_bundle'));
alter table public.payment_orders drop constraint if exists payment_orders_product_quantity_check;
alter table public.payment_orders add constraint payment_orders_product_quantity_check check (
  (product_kind='stickers' and range_quantity+custom_quantity>0) or
  (product_kind<>'stickers' and range_quantity=0 and custom_quantity=0));
alter table public.payment_orders add column if not exists cell_print_duration_days integer;
alter table public.payment_orders add column if not exists cell_print_device_limit integer;
alter table public.payment_orders add column if not exists cell_print_license_key text references public.cell_print_licenses(key);

alter table public.cell_print_licenses enable row level security;
alter table public.cell_print_activations enable row level security;
alter table public.cell_print_promocodes enable row level security;
alter table public.cell_print_announcements enable row level security;
alter table public.cell_print_releases enable row level security;
revoke all on table public.cell_print_licenses,public.cell_print_activations,public.cell_print_promocodes,public.cell_print_announcements,public.cell_print_releases from anon,authenticated;
grant select,insert,update,delete on table public.cell_print_licenses,public.cell_print_activations,public.cell_print_promocodes,public.cell_print_announcements,public.cell_print_releases to service_role;
grant usage,select on all sequences in schema public to service_role;

create or replace function public.activate_cell_print_license(p_key text,p_device_hash text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare lic public.cell_print_licenses; count_devices integer;
begin
  if p_device_hash !~ '^[0-9a-f]{64}$' then raise exception 'Invalid device'; end if;
  select * into lic from public.cell_print_licenses where key=upper(btrim(p_key)) for update;
  if not found or not lic.active then raise exception 'Invalid license'; end if;
  if lic.activated_at is null then
    update public.cell_print_licenses set activated_at=now(),expires_at=now()+make_interval(days=>duration_days) where id=lic.id returning * into lic;
  end if;
  if lic.expires_at<=now() then raise exception 'License expired'; end if;
  if not exists(select 1 from public.cell_print_activations where license_id=lic.id and device_hash=p_device_hash) then
    select count(*) into count_devices from public.cell_print_activations where license_id=lic.id;
    if count_devices>=lic.device_limit then raise exception 'Device limit reached'; end if;
    insert into public.cell_print_activations(license_id,device_hash) values(lic.id,p_device_hash);
  else update public.cell_print_activations set last_seen_at=now() where license_id=lic.id and device_hash=p_device_hash; end if;
  select count(*) into count_devices from public.cell_print_activations where license_id=lic.id;
  return jsonb_build_object('active',true,'expiresAt',lic.expires_at,'deviceLimit',lic.device_limit,'devicesUsed',count_devices,'serverTime',now());
end;$$;
revoke all on function public.activate_cell_print_license(text,text) from public,anon,authenticated;
grant execute on function public.activate_cell_print_license(text,text) to service_role;

create or replace function public.complete_cell_print_order(p_order_id uuid)
returns text language plpgsql security definer set search_path=public as $$
declare generated text; current_key text; days integer; devices integer; kind text;
begin
  perform pg_advisory_xact_lock(hashtext(p_order_id::text));
  select cell_print_license_key,cell_print_duration_days,cell_print_device_limit,product_kind into current_key,days,devices,kind from payment_orders where id=p_order_id for update;
  if not found or kind not in ('cell_print_program','cell_print_license','cell_print_bundle') then raise exception 'Order not found'; end if;
  if current_key is not null then return current_key; end if;
  loop
    generated:='CP-'||upper(substr(md5(random()::text||clock_timestamp()),1,4))||'-'||upper(substr(md5(random()::text||clock_timestamp()),1,4))||'-'||upper(substr(md5(random()::text||clock_timestamp()),1,4));
    begin insert into cell_print_licenses(key,duration_days,device_limit,source,note) values(generated,days,devices,'payment','Заказ '||p_order_id);exit; exception when unique_violation then null;end;
  end loop;
  update payment_orders set cell_print_license_key=generated,status='succeeded',paid_at=coalesce(paid_at,now()),updated_at=now() where id=p_order_id;
  return generated;
end;$$;
revoke all on function public.complete_cell_print_order(uuid) from public,anon,authenticated;
grant execute on function public.complete_cell_print_order(uuid) to service_role;

create or replace function public.consume_cell_print_promo(p_code text,p_scope text)
returns integer language plpgsql security definer set search_path=public as $$
declare discount integer;
begin
  update cell_print_promocodes set used=used+1 where code=upper(btrim(p_code)) and active and used<usage_limit and (expires_at is null or expires_at>now()) and (scope='all' or scope=p_scope) returning discount_percent into discount;
  if discount is null then raise exception 'Invalid promo'; end if; return discount;
end;$$;
revoke all on function public.consume_cell_print_promo(text,text) from public,anon,authenticated;
grant execute on function public.consume_cell_print_promo(text,text) to service_role;

commit;
