begin;

alter table public.sticker_access_codes
  add column if not exists range_usage_mode text not null default 'sticker'
  check (range_usage_mode in ('request', 'sticker'));

create table if not exists public.payment_settings (
  id boolean primary key default true check (id),
  enabled boolean not null default false,
  updated_at timestamptz not null default now()
);
insert into public.payment_settings(id, enabled) values (true, false) on conflict (id) do nothing;

create table if not exists public.payment_price_tiers (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('range', 'custom')),
  min_quantity integer not null check (min_quantity between 1 and 100),
  unit_price numeric(10,2) not null check (unit_price > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(kind, min_quantity)
);

create table if not exists public.payment_orders (
  id uuid primary key default gen_random_uuid(),
  public_token text not null unique,
  email text,
  range_quantity integer not null check (range_quantity between 0 and 100),
  custom_quantity integer not null check (custom_quantity between 0 and 100),
  amount numeric(10,2) not null check (amount > 0),
  currency text not null default 'RUB',
  pricing_snapshot jsonb not null,
  status text not null default 'pending' check (status in ('pending','waiting_for_capture','succeeded','canceled')),
  yookassa_payment_id text unique,
  idempotence_key uuid not null unique default gen_random_uuid(),
  confirmation_url text,
  access_code text unique references public.sticker_access_codes(code),
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  updated_at timestamptz not null default now(),
  check (range_quantity + custom_quantity > 0)
);
create index if not exists payment_orders_created_idx on public.payment_orders(created_at desc);

alter table public.payment_settings enable row level security;
alter table public.payment_price_tiers enable row level security;
alter table public.payment_orders enable row level security;
revoke all on table public.payment_settings, public.payment_price_tiers, public.payment_orders from anon, authenticated;
grant select, insert, update, delete on table public.payment_settings, public.payment_price_tiers, public.payment_orders to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.complete_payment_order(p_order_id uuid)
returns text language plpgsql security definer set search_path = public as $$
declare generated_code text; current_code text; rq integer; cq integer;
begin
  perform pg_advisory_xact_lock(hashtext(p_order_id::text));
  select access_code, range_quantity, custom_quantity into current_code, rq, cq
    from public.payment_orders where id = p_order_id for update;
  if not found then raise exception 'Order not found'; end if;
  if current_code is not null then return current_code; end if;
  loop
    generated_code := lpad(floor(random() * 1000000)::integer::text, 6, '0');
    begin
      insert into public.sticker_access_codes(
        code, name, active, range_generation_limit, custom_generation_limit, range_usage_mode
      ) values (generated_code, 'Покупка ' || p_order_id::text, true, rq, cq, 'sticker');
      exit;
    exception when unique_violation then null;
    end;
  end loop;
  update public.payment_orders set access_code = generated_code, status = 'succeeded',
    paid_at = coalesce(paid_at, now()), updated_at = now() where id = p_order_id;
  return generated_code;
end;
$$;
revoke all on function public.complete_payment_order(uuid) from public, anon, authenticated;
grant execute on function public.complete_payment_order(uuid) to service_role;

create or replace function public.consume_sticker_access(p_code text, p_kind text, p_quantity integer)
returns void language plpgsql security definer set search_path = public as $$
declare changed integer; units integer;
begin
  if p_kind not in ('range','custom') or p_quantity < 1 then raise exception 'Invalid access consumption'; end if;
  if p_kind = 'range' then
    update public.sticker_access_codes
       set range_generation_used = range_generation_used + p_quantity,
           range_usage_mode = 'sticker'
     where code = p_code and active
       and range_generation_used + p_quantity <= range_generation_limit;
  else
    update public.sticker_access_codes set custom_generation_used = custom_generation_used + p_quantity
    where code = p_code and active and custom_generation_used + p_quantity <= custom_generation_limit;
  end if;
  get diagnostics changed = row_count;
  if changed = 0 then raise exception 'Access code limit exceeded'; end if;
end;
$$;
revoke all on function public.consume_sticker_access(text,text,integer) from public, anon, authenticated;
grant execute on function public.consume_sticker_access(text,text,integer) to service_role;

create or replace function public.allocate_return_stickers(p_quantity integer,p_requester_hash text,p_access_code text default null)
returns table(batch_id uuid,code text,free_remaining integer)
language plpgsql security definer set search_path=public as $$
declare new_batch uuid; available_count integer; used_today integer; used_free integer; normalized_access_code text; access_updated integer;
begin
  if p_quantity<1 or p_quantity>100 or length(p_requester_hash)<>64 then raise exception 'Invalid allocation request'; end if;
  normalized_access_code:=nullif(btrim(coalesce(p_access_code,'')),'');
  perform pg_advisory_xact_lock(hashtext(p_requester_hash)); perform pg_advisory_xact_lock(hashtext('return_sticker_pool'));
  if normalized_access_code is null then
    select coalesce(sum(b.quantity),0)::integer into used_free from public.return_sticker_batches b where b.requester_hash=p_requester_hash and b.access_code is null and b.generation_kind='range';
    if used_free+p_quantity>1 then raise exception 'Sticker access code required'; end if;
  elsif not exists(select 1 from public.sticker_access_codes a where a.code=normalized_access_code and a.active) then raise exception 'Invalid sticker access code';
  else
    update public.sticker_access_codes a set range_generation_used=a.range_generation_used+p_quantity, range_usage_mode='sticker'
      where a.code=normalized_access_code and a.active and a.range_generation_used+p_quantity<=a.range_generation_limit;
    get diagnostics access_updated=row_count; if access_updated=0 then raise exception 'Access code range limit exceeded'; end if;
  end if;
  select coalesce(sum(b.quantity),0)::integer into used_today from public.return_sticker_batches b where b.requester_hash=p_requester_hash and b.created_at>=now()-interval '24 hours';
  if used_today+p_quantity>200 then raise exception 'Daily sticker limit exceeded'; end if;
  select count(*) into available_count from(select 1 from public.return_sticker_codes c where c.batch_id is null limit p_quantity)x;
  if available_count<p_quantity then raise exception 'Not enough unused sticker codes'; end if;
  insert into public.return_sticker_batches(quantity,requester_hash,access_code,generation_kind) values(p_quantity,p_requester_hash,normalized_access_code,'range') returning id into new_batch;
  return query with selected as(select c.code from public.return_sticker_codes c where c.batch_id is null order by c.code limit p_quantity for update skip locked),updated as(update public.return_sticker_codes c set batch_id=new_batch,allocated_at=now() from selected s where c.code=s.code returning c.code)
  select new_batch,updated.code::text,case when normalized_access_code is null then greatest(1-used_free-p_quantity,0) else 0 end from updated order by updated.code;
end;$$;
revoke all on function public.allocate_return_stickers(integer,text,text) from public,anon,authenticated;
grant execute on function public.allocate_return_stickers(integer,text,text) to service_role;

commit;
