begin;

-- Эта миграция также чинит базы, где миграция program_purchase была пропущена.
alter table public.payment_orders
  add column if not exists product_kind text not null default 'stickers'
  check (product_kind in ('stickers', 'program'));

alter table public.payment_orders drop constraint if exists payment_orders_check;
alter table public.payment_orders drop constraint if exists payment_orders_product_quantity_check;
alter table public.payment_orders
  add constraint payment_orders_product_quantity_check check (
    (product_kind = 'stickers' and range_quantity + custom_quantity > 0)
    or (product_kind = 'program' and range_quantity = 0 and custom_quantity = 0)
  );

create table if not exists public.program_promocodes (
  id bigint generated by default as identity primary key,
  code text not null unique check (code = upper(code) and code ~ '^[A-Z0-9_-]{3,32}$'),
  usage_limit integer not null default 1 check (usage_limit between 1 and 100000),
  used integer not null default 0 check (used between 0 and usage_limit),
  active boolean not null default true,
  note text not null default '' check (char_length(note) <= 200),
  created_at timestamptz not null default now()
);

alter table public.payment_orders drop constraint if exists payment_orders_amount_check;
alter table public.payment_orders add constraint payment_orders_amount_check check (amount >= 0);
alter table public.payment_orders add column if not exists promo_code text;

alter table public.program_promocodes enable row level security;
revoke all on table public.program_promocodes from anon, authenticated;
grant select, insert, update, delete on table public.program_promocodes to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.redeem_program_promocode(p_code text, p_public_token text)
returns void language plpgsql security definer set search_path = public as $$
declare normalized text; changed integer;
begin
  normalized := upper(btrim(coalesce(p_code, '')));
  if normalized !~ '^[A-Z0-9_-]{3,32}$' or length(p_public_token) < 40 then
    raise exception 'Invalid promo code';
  end if;
  update public.program_promocodes
     set used = used + 1
   where code = normalized and active and used < usage_limit;
  get diagnostics changed = row_count;
  if changed = 0 then raise exception 'Invalid promo code'; end if;
  insert into public.payment_orders(public_token, range_quantity, custom_quantity, amount,
    pricing_snapshot, status, product_kind, promo_code, paid_at)
  values(p_public_token, 0, 0, 0, jsonb_build_object('program',jsonb_build_object('total',0),
    'promoCode',normalized,'total',0), 'succeeded', 'program', normalized, now());
end;
$$;
revoke all on function public.redeem_program_promocode(text,text) from public, anon, authenticated;
grant execute on function public.redeem_program_promocode(text,text) to service_role;

commit;
