begin;

create table if not exists public.license_keys (
  id bigint generated by default as identity primary key,
  key text not null unique,
  usage_limit integer not null check (usage_limit > 0),
  used integer not null default 0 check (used >= 0),
  active boolean not null default true,
  note text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  text text not null check (length(btrim(text)) > 0),
  url text not null default '',
  button text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.trial_claims (
  hwid text primary key,
  claimed_at timestamptz not null default now()
);

create table if not exists public.site_stats (
  id smallint primary key default 1 check (id = 1),
  total_visits bigint not null default 0 check (total_visits >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_visitors (
  visitor_id text primary key,
  visit_count bigint not null default 0 check (visit_count >= 0),
  first_visit timestamptz not null default now(),
  last_visit timestamptz not null default now()
);

insert into public.site_stats (id, total_visits)
values (1, 0)
on conflict (id) do nothing;

alter table public.license_keys enable row level security;
alter table public.announcements enable row level security;
alter table public.trial_claims enable row level security;
alter table public.site_stats enable row level security;
alter table public.site_visitors enable row level security;

revoke all on table public.license_keys from anon, authenticated;
revoke all on table public.announcements from anon, authenticated;
revoke all on table public.trial_claims from anon, authenticated;
revoke all on table public.site_stats from anon, authenticated;
revoke all on table public.site_visitors from anon, authenticated;

grant select, insert, update, delete on table public.license_keys to service_role;
grant select, insert, update, delete on table public.announcements to service_role;
grant select, insert, update, delete on table public.trial_claims to service_role;
grant select, insert, update, delete on table public.site_stats to service_role;
grant select, insert, update, delete on table public.site_visitors to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.consume_license(p_key text)
returns setof public.license_keys
language sql
security definer
set search_path = public
as $$
  update public.license_keys
     set used = used + 1
   where key = p_key
     and active = true
     and used < usage_limit
  returning *;
$$;

create or replace function public.claim_trial(p_hwid text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.trial_claims (hwid)
  values (p_hwid)
  on conflict (hwid) do nothing;
  return found;
end;
$$;

create or replace function public.record_visit(p_visitor_id text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_total bigint;
begin
  update public.site_stats
     set total_visits = total_visits + 1,
         updated_at = now()
   where id = 1
  returning total_visits into new_total;

  insert into public.site_visitors (
    visitor_id, visit_count, first_visit, last_visit
  )
  values (p_visitor_id, 1, now(), now())
  on conflict (visitor_id) do update
    set visit_count = public.site_visitors.visit_count + 1,
        last_visit = now();

  return new_total;
end;
$$;

revoke all on function public.consume_license(text) from public, anon, authenticated;
revoke all on function public.claim_trial(text) from public, anon, authenticated;
revoke all on function public.record_visit(text) from public, anon, authenticated;

grant execute on function public.consume_license(text) to service_role;
grant execute on function public.claim_trial(text) to service_role;
grant execute on function public.record_visit(text) to service_role;

commit;
