begin;

alter table public.payment_orders
  add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.sticker_access_codes
  add column if not exists owner_user_id uuid references auth.users(id) on delete set null;
alter table public.license_keys
  add column if not exists owner_user_id uuid references auth.users(id) on delete set null;
alter table public.cell_print_licenses
  add column if not exists owner_user_id uuid references auth.users(id) on delete set null;

create index if not exists payment_orders_user_idx on public.payment_orders(user_id, created_at desc);
create index if not exists sticker_access_owner_idx on public.sticker_access_codes(owner_user_id);
create index if not exists license_keys_owner_idx on public.license_keys(owner_user_id);
create index if not exists cell_print_licenses_owner_idx on public.cell_print_licenses(owner_user_id);

create table if not exists public.user_generation_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_entry_id text not null check (char_length(client_entry_id) between 1 and 120),
  mode text not null check (mode in ('range','custom')),
  created_at timestamptz not null,
  payload jsonb not null,
  imported_at timestamptz not null default now(),
  unique(user_id, client_entry_id)
);

create table if not exists public.user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  thermal_print_settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.user_generation_history enable row level security;
alter table public.user_preferences enable row level security;
revoke all on table public.user_generation_history, public.user_preferences from anon, authenticated;
grant select, insert, update, delete on table public.user_generation_history, public.user_preferences to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.claim_user_asset(p_user_id uuid, p_kind text, p_value text)
returns jsonb language plpgsql security definer set search_path=public,auth as $$
declare changed integer; linked_order uuid;
begin
  if not exists(select 1 from auth.users where id=p_user_id and email_confirmed_at is not null) then
    raise exception 'User is not confirmed';
  end if;
  if p_kind='sticker' then
    update public.sticker_access_codes set owner_user_id=p_user_id
      where code=btrim(p_value) and (owner_user_id is null or owner_user_id=p_user_id);
    get diagnostics changed=row_count;
    if changed=0 then
      if exists(select 1 from public.sticker_access_codes where code=btrim(p_value)) then raise exception 'Asset belongs to another user'; end if;
      raise exception 'Asset not found';
    end if;
    update public.payment_orders set user_id=p_user_id
      where access_code=btrim(p_value) and (user_id is null or user_id=p_user_id) returning id into linked_order;
  elsif p_kind='program' then
    update public.license_keys set owner_user_id=p_user_id
      where key=upper(btrim(p_value)) and (owner_user_id is null or owner_user_id=p_user_id);
    get diagnostics changed=row_count;
    if changed=0 then
      if exists(select 1 from public.license_keys where key=upper(btrim(p_value))) then raise exception 'Asset belongs to another user'; end if;
      raise exception 'Asset not found';
    end if;
    update public.payment_orders set user_id=p_user_id
      where program_license_key=upper(btrim(p_value)) and (user_id is null or user_id=p_user_id) returning id into linked_order;
  elsif p_kind='cell_print' then
    update public.cell_print_licenses set owner_user_id=p_user_id
      where key=upper(btrim(p_value)) and (owner_user_id is null or owner_user_id=p_user_id);
    get diagnostics changed=row_count;
    if changed=0 then
      if exists(select 1 from public.cell_print_licenses where key=upper(btrim(p_value))) then raise exception 'Asset belongs to another user'; end if;
      raise exception 'Asset not found';
    end if;
    update public.payment_orders set user_id=p_user_id
      where cell_print_license_key=upper(btrim(p_value)) and (user_id is null or user_id=p_user_id) returning id into linked_order;
  elsif p_kind='order' then
    update public.payment_orders set user_id=p_user_id
      where public_token=p_value and status='succeeded' and (user_id is null or user_id=p_user_id)
      returning id into linked_order;
    get diagnostics changed=row_count;
    if changed=0 then
      if exists(select 1 from public.payment_orders where public_token=p_value and user_id is distinct from p_user_id) then raise exception 'Asset belongs to another user'; end if;
      raise exception 'Order not found';
    end if;
    update public.sticker_access_codes a set owner_user_id=p_user_id from public.payment_orders o
      where o.id=linked_order and a.code=o.access_code and (a.owner_user_id is null or a.owner_user_id=p_user_id);
    update public.license_keys a set owner_user_id=p_user_id from public.payment_orders o
      where o.id=linked_order and a.key=o.program_license_key and (a.owner_user_id is null or a.owner_user_id=p_user_id);
    update public.cell_print_licenses a set owner_user_id=p_user_id from public.payment_orders o
      where o.id=linked_order and a.key=o.cell_print_license_key and (a.owner_user_id is null or a.owner_user_id=p_user_id);
  else raise exception 'Invalid asset kind';
  end if;
  return jsonb_build_object('claimed',true,'kind',p_kind);
end;$$;
revoke all on function public.claim_user_asset(uuid,text,text) from public,anon,authenticated;
grant execute on function public.claim_user_asset(uuid,text,text) to service_role;

commit;
